[book]
title = "Why-first Rust Guide"
authors = ["shinagawa-web"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/shinagawa-web/rust-guide"
edit-url-template = "https://github.com/shinagawa-web/rust-guide/edit/main/en/src/{path}"
